import streamlit as st
from datetime import datetime, timedelta
from uuid import uuid4
import logging
from src.agent.graph import graph_agent
from langchain_core.messages import AIMessage, HumanMessage

# Replace this with your actual agent (LangGraph or LangChain agent)
# from your_agent_file import graph_agent  # <-- You must define/import your agent properly here

# Setup logger
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Set page configuration
st.set_page_config(page_title="Chatbot", layout="centered")
st.title("🤖 TrinX Chatbot")
# Session management
SESSION_TIMEOUT = timedelta(minutes=10)
now = datetime.now()

if "thread_id" not in st.session_state or "last_active" not in st.session_state:
    st.session_state.thread_id = str(uuid4())
    st.session_state.messages = []
    st.session_state.last_active = now
    logger.info(f"New session started with thread_id: {st.session_state.thread_id}")
elif now - st.session_state.last_active > SESSION_TIMEOUT:
    logger.warning("Session timed out. Creating new session.")
    st.session_state.thread_id = str(uuid4())
    st.session_state.messages = []
    st.session_state.last_active = now
    logger.info(f"New session started with thread_id: {st.session_state.thread_id}")

st.session_state.last_active = now

# Display previous messages
for msg in st.session_state.messages:
    role = "assistant" if isinstance(msg, AIMessage) else "user"
    with st.chat_message(role):
        st.markdown(msg.content)

# Chat input : user input
user_input = st.chat_input(
    placeholder="Ask a question…",
)

if user_input:
    st.chat_message("user").markdown(user_input)
    logger.info(f"User question: {user_input}")

    user_msg = HumanMessage(content=user_input)
    st.session_state.messages.append(user_msg)

    try:
        logger.info("Invoking graph agent")
        result = graph_agent.invoke(
            {"messages": [user_msg]},
            config={"configurable": {"thread_id": st.session_state.thread_id}},
        )
        logger.info("Graph agent invocation successful")

        # Display assistant message
        ai_msg = next(
            (m for m in reversed(result["messages"]) if isinstance(m, AIMessage)), None
        )
        if ai_msg:
            st.chat_message("assistant").markdown(ai_msg.content)
            st.session_state.messages.append(ai_msg)
            logger.info(f"AI response: {ai_msg.content}")
        else:
            st.chat_message("assistant").markdown("⚠️ No response generated.")
            logger.warning("No response generated by the AI.")
    except Exception as e:
        logger.error(f"Error invoking graph agent: {e}")
        st.chat_message("assistant").markdown(f"❌ Error: `{e}`")
