name: CI/CD Pipeline 

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    name: Continuous Integration
    runs-on: ubuntu-latest

    env:   # secrets & vars available for pytest
      GROQ_MODEL: ${{ secrets.GROQ_MODEL }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}
      LANGSMITH_ENDPOINT: ${{ secrets.LANGSMITH_ENDPOINT }}
      LANGSMITH_PROJECT: ${{ secrets.LANGSMITH_PROJECT }}
      Tavily_API_KEY: ${{ secrets.Tavily_API_KEY }}
      SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
      CORS_ORIGINS: ${{ vars.CORS_ORIGINS }}
      PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install uv
          uv sync --all-extras

      - name: Lint code with Ruff
        run: uv run ruff check .

      - name: Run tests with pytest
        run: uv run pytest -v

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release Directory and Copy Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "."
          target: "/var/www/apps/alpha_releases/release_${{ github.run_number }}_${{ github.run_attempt }}" # Use a consistent, non-dynamic path for scp-action
      
      - name: Install Dependencies and Activate Release
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            set -e
            export PATH="$HOME/.local/bin:$PATH"
            # Use the run number and attempt to find the release directory
            RELEASE_DIR="/var/www/apps/alpha_releases/release_${{ github.run_number }}_${{ github.run_attempt }}"
            APP_SYMLINK="/var/www/apps/alpha"
            
            echo "Activating release in: $RELEASE_DIR"
            
            # Install dependencies inside the new release folder
            cd $RELEASE_DIR

            # Install 'uv' with pip
            pip install uv

            uv sync --frozen
            
            # Update symlink for zero downtime
            ln -sfn $RELEASE_DIR $APP_SYMLINK
            
            # Restart app service
            sudo systemctl daemon-reload
            sudo systemctl restart alpha.service
            
            echo "✅ Deployment complete"
